import { TRPCProvider } from '../utils/trpc-provider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <TRPCProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </TRPCProvider>
  )
}
